<?php

namespace Classificacao\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReuniaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReuniaoRepository extends EntityRepository
{
}
