<?php

namespace Pessoa\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilhoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilhoRepository extends EntityRepository
{
    
}
