<a class="btn btn-success" href="<?php echo $this->url('pessoa/default', array('controller' => 'tesouraria', 'action' => 'inserir')); ?>">Novo Financeiro</a>
<br>

<?php

if ($this->success) {
    echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}
if ($this->error) {
    echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}
?>
<table class="table table-bordered table-striped table-hover table-condensed">
    <caption>Todos os Financeiros</caption>
    <thead>
        <tr class="subtitulo">
            <th>Código</th>
            <th>Pessoa</th>
            <th>Data</th>
            <th>Débito</th>
            <th>Crédito</th>
            <th>Saldo</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php
        /**
         * @var $entity \Pessoa\Entity\Tesouraria
         */
        
        
        ?>
        <?php if ($this->data): ?>
            <?php foreach ($this->data as $entity): ?>
                <tr>

                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getPessoa()->getNome(); ?></td>
                    <td><?php echo ($entity->getData())? $entity->getData()->format('d/m/Y'): '---'; ?></td>
                    <td><?php echo ($entity->getDebito())? $entity->getDebito(): '0'; ?></td>
                    <td><?php echo ($entity->getCredito())? $entity->getCredito(): '0'; ?></td>
                    <td><?php $credito = $entity->getCredito(); 
                        $debito = $entity->getDebito();
                        echo $credito - $debito;
                        ?>
                    
                    
                    
                    </td>
                    <td>
                        <a class="btn btn-success" href="<?php echo $this->url('pessoa/default', array('controller' => 'tesouraria', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-pencil"></i></a>

                        <a class="btn btn-danger" href="<?php echo $this->url('pessoa/default', array('controller' => 'tesouraria', 'action' => 'excluir', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-remove-sign"></i></a>

                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <p>Nenhum registro encontrado !!</p>
    <?php endif; ?>
</tbody>
</table>
<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'pessoa/paginator')); ?>
<br>
<a class="btn btn-success" href="<?php echo $this->url('pessoa/default', array('controller' => 'pessoas')); ?>">Voltar</a>
<style type="text/css">
    .subtitulo{background: lightgray}
</style>