<a class="btn btn-success" href="<?php echo $this->url('membro/default', array('controller' => 'membro', 'action' => 'inserir')); ?>">Novo Membro Comissão</a>
<br>

<?php
if ($this->success) {
    echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}
if ($this->error) {
    echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
}
?>
<table class="table table-bordered table-striped table-hover table-condensed">
    <caption>Todos os Membros</caption>
    <thead>
        <tr class="subtitulo">
            <th>Código</th>
            <th>Comissão</th>
            <th>Membros da Comissão</th>
            <th>Cargo dos Membros</th>
            <th>Data Inicio</th>
            <th>Data Fim</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php
        /**
         * @var $entity \Membro\Entity\Membro
         */
        ?>
        <?php if ($this->data): ?>
            <?php foreach ($this->data as $entity): ?>
                <tr>
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getComissao()->getDescricao() ?></td>
                    <td><textarea cols="25" rows="5" readonly="readonly"><?php echo ($entity->getMembro()) ? $entity->getMembro() : '****'; ?>" </textarea></td>
                    <td><textarea cols="25" rows="5" readonly="readonly"><?php echo ($entity->getCargo()) ? $entity->getCargo() : '****'; ?></textarea></td>
                    <td><?php echo ($entity->getDataInicio()) ? $entity->getDataInicio() : '****'; ?></td>
                    <td><?php echo ($entity->getDataFim()) ? $entity->getDataFim() : '****'; ?></td>
                    <td>
                        <a class="btn btn-success" href="<?php echo $this->url('membro/default', array('controller' => 'membro', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a class="btn btn-danger" href="<?php echo $this->url('membro/default', array('controller' => 'membro', 'action' => 'excluir', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-remove-sign"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <p>Nenhum registro encontrado !!</p>
    <?php endif; ?>
</tbody>
</table>
<a class="btn btn-success" href="<?php echo $this->url('sonuser-admin/default', array('controller' => 'users')); ?>">Voltar</a>

<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'membro/paginator')); ?>
<style type="text/css">
    .subtitulo{background: lightgray}
</style>