<?php

namespace Membro\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembroRepository extends EntityRepository
{
}
